"""
Text-to-Structure Generator for MOF Design

使用LLM理解自然语言描述，生成MOF结构
"""

import json
import numpy as np
from typing import Dict, List, Optional, Tuple
import warnings
warnings.filterwarnings('ignore')


class MockLLM:
    """
    模拟LLM API（用于演示）

    实际使用时，替换为真实的LLM API：
    - OpenAI GPT-4
    - Anthropic Claude
    - 本地部署的LLaMA等
    """

    def generate(self, prompt: str, **kwargs) -> str:
        """模拟LLM生成"""
        # 这里返回预定义的响应用于演示
        if "extract parameters" in prompt.lower():
            return json.dumps({
                "metal": "Cu",
                "linker": "BDC (1,4-benzenedicarboxylate)",
                "topology": "paddle-wheel",
                "target_application": "CO2 capture",
                "desired_properties": {
                    "high_surface_area": True,
                    "open_metal_sites": True
                }
            })
        elif "similar mofs" in prompt.lower():
            return "HKUST-1, MOF-505, PCN-6"
        else:
            return "Response generated by mock LLM"


class Text2StructureGenerator:
    """
    文本到结构生成器

    工作流程：
    1. LLM理解文本描述
    2. 提取结构参数
    3. 检索相似MOF或生成新结构
    4. 预测性质并验证
    """

    def __init__(
        self,
        llm_model: Optional[object] = None,
        mof_database: Optional[Dict] = None,
        use_generation_model: bool = False
    ):
        """
        初始化生成器

        参数:
            llm_model: LLM模型实例（如果为None，使用MockLLM）
            mof_database: MOF数据库（用于检索）
            use_generation_model: 是否使用生成模型（VAE/Diffusion）
        """
        self.llm = llm_model if llm_model is not None else MockLLM()
        self.mof_database = mof_database if mof_database is not None else self._init_mock_database()
        self.use_generation_model = use_generation_model

        # 如果使用生成模型，尝试导入
        if use_generation_model:
            try:
                from ..generative_models.mof_vae import MOFVAE
                self.vae_model = None  # 需要加载训练好的模型
            except:
                print("Warning: Generation model not available. Using retrieval only.")
                self.use_generation_model = False

    def _init_mock_database(self) -> Dict:
        """初始化模拟MOF数据库"""
        return {
            "HKUST-1": {
                "metal": "Cu",
                "linker": "BTC",
                "topology": "tbo",
                "surface_area": 1850,
                "co2_uptake": 6.5,
                "description": "Copper-based MOF with paddle-wheel SBU"
            },
            "MOF-5": {
                "metal": "Zn",
                "linker": "BDC",
                "topology": "pcu",
                "surface_area": 3800,
                "co2_uptake": 4.5,
                "description": "Zinc-based MOF with tetrahedral clusters"
            },
            "UiO-66": {
                "metal": "Zr",
                "linker": "BDC",
                "topology": "fcu",
                "surface_area": 1200,
                "co2_uptake": 3.0,
                "description": "Zirconium-based MOF with high stability"
            }
        }

    def generate_from_text(
        self,
        text_description: str,
        method: str = "hybrid",  # "retrieval", "generation", "hybrid"
        top_k: int = 3,
        verbose: bool = True
    ) -> Dict:
        """
        从文本描述生成MOF结构

        参数:
            text_description: 自然语言描述
            method: 生成方法（retrieval/generation/hybrid）
            top_k: 返回候选数量
            verbose: 是否打印详细信息

        返回:
            result: 包含候选MOF和元数据的字典
        """
        if verbose:
            print(f"[Text-to-Structure] Processing: {text_description}\n")

        # Step 1: 提取结构参数
        params = self.extract_parameters(text_description)
        if verbose:
            print(f"[Step 1] Extracted parameters:")
            print(json.dumps(params, indent=2))
            print()

        # Step 2: 生成候选
        if method == "retrieval":
            candidates = self.retrieve_candidates(params, top_k)
        elif method == "generation":
            candidates = self.generate_candidates(params, top_k)
        else:  # hybrid
            retrieval_cands = self.retrieve_candidates(params, top_k // 2 + 1)
            if self.use_generation_model:
                generation_cands = self.generate_candidates(params, top_k // 2)
                candidates = retrieval_cands + generation_cands
            else:
                candidates = retrieval_cands

        if verbose:
            print(f"[Step 2] Generated {len(candidates)} candidates\n")

        # Step 3: 预测性质并排序
        ranked_candidates = self.predict_and_rank(candidates, params)

        if verbose:
            print(f"[Step 3] Ranked candidates:")
            for i, cand in enumerate(ranked_candidates[:top_k]):
                print(f"{i+1}. {cand['name']} - Score: {cand['score']:.2f}")
                print(f"   Metal: {cand['metal']}, Linker: {cand['linker']}")
                print(f"   Predicted CO2 uptake: {cand['predicted_co2']:.2f} mmol/g\n")

        result = {
            "query": text_description,
            "extracted_parameters": params,
            "candidates": ranked_candidates[:top_k],
            "method": method
        }

        return result

    def extract_parameters(self, text: str) -> Dict:
        """
        使用LLM从文本中提取结构参数

        参数:
            text: 文本描述

        返回:
            params: 提取的参数字典
        """
        prompt = f"""
        Extract MOF design parameters from the following description:

        "{text}"

        Please identify:
        1. Metal center (e.g., Cu, Zn, Zr)
        2. Organic linker (e.g., BDC, BTC, DOBDC)
        3. Topology/SBU (e.g., paddle-wheel, tetrahedral, octahedral)
        4. Target application
        5. Desired properties

        Return as JSON format.
        """

        response = self.llm.generate(prompt)

        try:
            params = json.loads(response)
        except:
            # 如果LLM返回格式不是JSON，使用简单解析
            params = {
                "metal": "Cu" if "copper" in text.lower() or "cu" in text.lower() else "Unknown",
                "linker": "BDC",
                "topology": "paddle-wheel" if "paddle" in text.lower() else "Unknown",
                "target_application": "CO2 capture" if "co2" in text.lower() else "Unknown"
            }

        return params

    def retrieve_candidates(self, params: Dict, top_k: int = 3) -> List[Dict]:
        """
        从数据库检索相似MOF

        参数:
            params: 提取的参数
            top_k: 返回数量

        返回:
            candidates: MOF候选列表
        """
        candidates = []

        # 简单的相似度匹配
        for name, mof_data in self.mof_database.items():
            score = 0.0

            # 金属匹配
            if "metal" in params and params["metal"].lower() in mof_data["metal"].lower():
                score += 3.0

            # 配体匹配
            if "linker" in params and params["linker"][:3].lower() in mof_data["linker"].lower():
                score += 2.0

            # 拓扑匹配
            if "topology" in params and params["topology"].lower() in mof_data.get("topology", "").lower():
                score += 1.5

            # 应用匹配（基于CO2吸附）
            if "co2" in params.get("target_application", "").lower():
                score += mof_data.get("co2_uptake", 0) / 10.0

            candidate = {
                "name": name,
                "metal": mof_data["metal"],
                "linker": mof_data["linker"],
                "topology": mof_data.get("topology", "Unknown"),
                "surface_area": mof_data.get("surface_area", 0),
                "predicted_co2": mof_data.get("co2_uptake", 0),
                "score": score,
                "source": "database"
            }
            candidates.append(candidate)

        # 按分数排序
        candidates.sort(key=lambda x: x["score"], reverse=True)

        return candidates[:top_k]

    def generate_candidates(self, params: Dict, num_candidates: int = 3) -> List[Dict]:
        """
        使用生成模型生成新MOF结构

        参数:
            params: 设计参数
            num_candidates: 生成数量

        返回:
            candidates: 生成的MOF候选
        """
        if not self.use_generation_model or self.vae_model is None:
            print("Generation model not available. Using parametric generation.")
            return self._parametric_generation(params, num_candidates)

        # 使用VAE生成
        # z = self.vae_model.sample(num_candidates)
        # structures = self.vae_model.decode(z)

        # 返回生成的结构（简化版）
        return self._parametric_generation(params, num_candidates)

    def _parametric_generation(self, params: Dict, num: int) -> List[Dict]:
        """基于参数的简单生成（演示用）"""
        candidates = []

        for i in range(num):
            candidate = {
                "name": f"Generated-MOF-{i+1}",
                "metal": params.get("metal", "Unknown"),
                "linker": params.get("linker", "Unknown"),
                "topology": params.get("topology", "Unknown"),
                "surface_area": np.random.randint(1000, 4000),
                "predicted_co2": np.random.uniform(2.0, 7.0),
                "score": np.random.uniform(3.0, 5.0),
                "source": "generated"
            }
            candidates.append(candidate)

        return candidates

    def predict_and_rank(self, candidates: List[Dict], params: Dict) -> List[Dict]:
        """
        预测候选MOF的性质并排序

        参数:
            candidates: MOF候选列表
            params: 设计参数

        返回:
            ranked_candidates: 排序后的候选列表
        """
        # 简化的性质预测（实际应使用训练好的ML模型）
        for candidate in candidates:
            # 基于表面积和金属类型的简单估计
            if "predicted_co2" not in candidate or candidate["predicted_co2"] == 0:
                sa = candidate.get("surface_area", 1000)
                co2_estimate = 0.001 * sa + np.random.uniform(-0.5, 0.5)

                # 开放金属位点加成
                if candidate["metal"] in ["Cu", "Fe", "Co", "Ni"]:
                    co2_estimate *= 1.3

                candidate["predicted_co2"] = max(0.5, co2_estimate)

            # 计算综合分数
            if "co2" in params.get("target_application", "").lower():
                candidate["score"] = (
                    candidate.get("score", 0) +
                    candidate["predicted_co2"] * 0.5
                )

        # 排序
        candidates.sort(key=lambda x: x["score"], reverse=True)

        return candidates


class StructureValidator:
    """
    MOF结构验证器

    验证生成的MOF结构是否合理
    """

    @staticmethod
    def validate_structure(mof_data: Dict) -> Tuple[bool, List[str]]:
        """
        验证MOF结构

        返回:
            is_valid: 是否有效
            issues: 问题列表
        """
        issues = []

        # 检查必要字段
        required_fields = ["metal", "linker"]
        for field in required_fields:
            if field not in mof_data or mof_data[field] == "Unknown":
                issues.append(f"Missing or unknown {field}")

        # 检查性质合理性
        if "surface_area" in mof_data:
            sa = mof_data["surface_area"]
            if sa < 0 or sa > 10000:
                issues.append(f"Unrealistic surface area: {sa} m²/g")

        if "predicted_co2" in mof_data:
            co2 = mof_data["predicted_co2"]
            if co2 < 0 or co2 > 50:
                issues.append(f"Unrealistic CO2 uptake: {co2} mmol/g")

        is_valid = len(issues) == 0

        return is_valid, issues


# ===== 示例和测试 =====

def example_text_to_structure():
    """示例：文本到结构生成"""
    print("=" * 70)
    print("Text-to-Structure Generation Example")
    print("=" * 70)
    print()

    # 初始化生成器
    generator = Text2StructureGenerator()

    # 测试查询
    queries = [
        "Design a copper-based MOF with paddle-wheel clusters for CO2 capture",
        "I need a water-stable Zr-MOF with high surface area",
        "Generate a MOF with open metal sites for selective gas separation"
    ]

    for query in queries:
        print(f"\nQuery: \"{query}\"")
        print("-" * 70)

        result = generator.generate_from_text(
            query,
            method="hybrid",
            top_k=3,
            verbose=True
        )

        # 验证top候选
        top_candidate = result["candidates"][0]
        is_valid, issues = StructureValidator.validate_structure(top_candidate)

        print(f"Top candidate validation: {'✓ Valid' if is_valid else '✗ Invalid'}")
        if issues:
            print(f"Issues: {', '.join(issues)}")
        print()


if __name__ == "__main__":
    example_text_to_structure()

    print("\n" + "=" * 70)
    print("✓ Text-to-Structure tool is ready!")
    print("=" * 70)
    print("\nTo use with a real LLM:")
    print("1. Install: pip install openai  # or anthropic, etc.")
    print("2. Initialize with API key:")
    print("   from openai import OpenAI")
    print("   llm = OpenAI(api_key='your-key')")
    print("   generator = Text2StructureGenerator(llm_model=llm)")
    print("3. Generate: result = generator.generate_from_text('your query')")
